import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/navbar";
import Footer from "@/components/Footer";
import { Manrope, Bricolage_Grotesque } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "PANTAZI - a software company",
  description: "Generated by create next app",
};

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  preload: true,
  weight: ["400","500","700","800"],
});

const inter = Manrope({
  subsets: ["latin"],
  variable: "--font-inter",
  preload: true,
  weight: ["400","500","700","800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans text-zinc-800 bg-white antialiased scroll-smooth`}>
        <Header />
        {children}
        <Footer />
        <SpeedInsights />
        <Toaster />
      </body>
    </html>
  );
}
